{{- if and .Values.rbac.create .Values.deploy }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cspmCollector.fullname" .}}
  labels:
{{ include "cspmCollector.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "cspmCollector.serviceAccountName" .}}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "cspmCollector.fullname" .}}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
