{{- if .Values.deploy }}
{{- if not ( include "cspmCollector.accessKeySecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cspmCollector.fullname" . }}
  labels:
{{ include "cspmCollector.labels" . | indent 4 }}
type: Opaque
data:
 access-key : {{ include "cspmCollector.accessKey" . | b64enc | quote }}
{{- end }}
{{- end }}
