{{- if and .Values.deploy .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cspmCollector.serviceAccountName" .}}
  labels:
{{ include "cspmCollector.labels" . | indent 4 }}
{{- end }}
