apiVersion: v2
name: cloud-bench
description: Sysdig Cloud Bench

type: application
version: 0.3.0
appVersion: 0.1.0
home: https://sysdig.com
icon: https://478h5m1yrfsa3bbe262u7muv-wpengine.netdna-ssl.com/wp-content/uploads/2019/02/Shovel_600px.png

maintainers:
  - name: yathi-sysdig
    email: yathindra.naik@sysdig.com
  - name: airadier
    email: alvaro.iradier@sysdig.com
