apiVersion: v2
name: harbor-scanner-sysdig-secure
description: Harbor Scanner for Sysdig Secure
type: application
version: 0.3.1
appVersion: 0.5.0
home: https://github.com/sysdiglabs/harbor-scanner-sysdig-secure
icon: https://478h5m1yrfsa3bbe262u7muv-wpengine.netdna-ssl.com/wp-content/uploads/2019/02/Shovel_600px.png
maintainers:
  - name: nestorsalceda
    email: nestor.salceda@sysdig.com
  - name: airadier
    email: alvaro.iradier@sysdig.com
