{{- if and .Values.nodeAnalyzer.deploy (not .Values.gke.autopilot) (include "nodeAnalyzer.deployHostScanner" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-host-scanner
  namespace: {{ include "nodeAnalyzer.namespace" . }}
  labels:
{{ include "nodeAnalyzer.labels" . | indent 4 }}
data:
  api_endpoint: https://{{ include "nodeAnalyzer.apiEndpoint" . }}
  cluster_name: {{ required "A valid clusterName is required" (include "nodeAnalyzer.clusterName" . ) }}
  {{- if hasKey .Values.global.sysdig "tags" }}
  {{- if .Values.global.sysdig.tags }}
  custom_tags: {{ include "agent.tags" . }}
  {{- end }}
  {{- end }}
  {{- if hasKey .Values.nodeAnalyzer.hostScanner "scanOnStart" }}
  scan_on_start: "{{ .Values.nodeAnalyzer.hostScanner.scanOnStart }}"
  {{- end }}
  {{- if .Values.nodeAnalyzer.hostScanner.dirsToScan }}
  dirs_to_scan: {{ .Values.nodeAnalyzer.hostScanner.dirsToScan }}
  {{- end }}
  {{- if .Values.nodeAnalyzer.hostScanner.additionalDirsToScan }}
  additional_dirs_to_scan: {{ .Values.nodeAnalyzer.hostScanner.additionalDirsToScan }}
  {{- end }}
  {{- if hasKey .Values.nodeAnalyzer "sslVerifyCertificate" }}
  ssl_verify_certificate: "{{ .Values.nodeAnalyzer.sslVerifyCertificate }}"
  {{- end }}
  debug: "{{ .Values.nodeAnalyzer.debug | default false }}"
  {{- if (.Values.nodeAnalyzer.httpProxy | default .Values.global.proxy.httpProxy) }}
  http_proxy: {{ .Values.nodeAnalyzer.httpProxy | default .Values.global.proxy.httpProxy }}
  {{- end -}}
  {{- if (.Values.nodeAnalyzer.httpsProxy | default .Values.global.proxy.httpsProxy) }}
  https_proxy: {{ .Values.nodeAnalyzer.httpsProxy | default .Values.global.proxy.httpsProxy }}
  {{- end -}}
  {{- if (.Values.nodeAnalyzer.noProxy | default .Values.global.proxy.noProxy) }}
  no_proxy: {{ .Values.nodeAnalyzer.noProxy | default .Values.global.proxy.noProxy }}
  {{- end -}}
  {{- if .Values.nodeAnalyzer.hostScanner.vulnerabilityDBVersion }}
  vuln_db_version: {{ .Values.nodeAnalyzer.hostScanner.vulnerabilityDBVersion | quote }}
  {{- end }}
{{- end }}
