{{ if .Values.nodeAnalyzer.cspmAnalyzer.deploy }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nodeAnalyzer.fullname" . }}-cspm-analyzer
  labels:
{{ include "nodeAnalyzer.labels" . | indent 4 }}
data:
{{- $env := "PRODUCTION" -}}
{{ if .Values.nodeAnalyzer.cspmAnalyzer.debug }}
  {{- $env = "DEVELOPMENT" -}}
{{ end}}
  environment: {{ $env }}
  external_nats_url: {{ include "nodeAnalyzer.natsUrl" . }}
  cluster_name: {{ required "A valid .Values.clusterName is required" .Values.clusterName }}
  agent_app_name: {{ include "nodeAnalyzer.name" . }}-node-analyzer
{{- end -}}