apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud-connector.fullname" . }}
  labels:
    {{- include "cloud-connector.labels" . | nindent 4 }}
data:
  cloud-connector.yaml: |
    rules:
{{ toYaml .Values.rules | indent 4 }}
    ingestors:
{{ toYaml .Values.ingestors | indent 4 }}
    notifiers:
{{ toYaml .Values.notifiers | indent 4 }}
