{{- if .Values.sysdig.secure.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor-scanner-sysdig-secure.fullname" . }}
  labels:
    {{- include "harbor-scanner-sysdig-secure.labels" . | nindent 4 }}
type: Opaque
data:
  sysdig_secure_api_token: {{ required "A valid .Values.sysdig.secure.apiToken is required" .Values.sysdig.secure.apiToken | b64enc | quote }}
{{- end }}
