{{- if and .Values.nodeAnalyzer.deploy (not (include "nodeAnalyzer.gke.autopilot" .)) (or .Values.nodeAnalyzer.runtimeScanner.deploy .Values.secure.vulnerabilityManagement.newEngineOnly) .Values.nodeAnalyzer.runtimeScanner.eveConnector.deploy }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nodeAnalyzer.fullname" . }}-eveconnector-api
  namespace: {{ include "nodeAnalyzer.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "nodeAnalyzer.name" . }}-eveconnector
{{ include "nodeAnalyzer.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.nodeAnalyzer.runtimeScanner.eveConnector.settings.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nodeAnalyzer.name" . }}-eveconnector
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/runtimeScanner/eveconnector-api-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/runtimeScanner/sysdig-eve-secret.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "nodeAnalyzer.name" . }}-eveconnector
{{ include "nodeAnalyzer.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ template "nodeAnalyzer.serviceAccountName" .}}
      {{- if .Values.nodeAnalyzer.runtimeScanner.eveConnector.priorityClassName }}
      priorityClassName: {{ .Values.nodeAnalyzer.runtimeScanner.eveConnector.priorityClassName | quote }}
      {{- end }}
      volumes:
        {{- if eq (include "sysdig.custom_ca.useValues"  (dict "global" .Values.global.ssl "component" .Values.nodeAnalyzer.ssl)) "true" }}
        - name: ca-cert
          secret:
            secretName: {{ include "nodeAnalyzer.fullname" . }}-eveconnector-ca
        {{- else if eq (include "sysdig.custom_ca.useExistingSecret"  (dict "global" .Values.global.ssl "component" .Values.nodeAnalyzer.ssl)) "true" }}
        - name: ca-cert
          secret:
            secretName: {{ include "sysdig.custom_ca.existingSecret" (dict "global" .Values.global.ssl "component" .Values.nodeAnalyzer.ssl) }}
        {{- else if eq (include "sysdig.custom_ca.useExistingConfigMap" (dict "global" .Values.global.ssl "component" .Values.nodeAnalyzer.ssl)) "true" }}
        - name: ca-cert
          configMap:
            name: {{ include "sysdig.custom_ca.existingConfigMap" (dict "global" .Values.global.ssl "component" .Values.nodeAnalyzer.ssl) }}
        {{- end }}
      containers:
      - name: {{ include "nodeAnalyzer.name" . }}-eveconnector-api
        image: {{ template "nodeAnalyzer.image.eveConnector" . }}
        imagePullPolicy: {{ .Values.nodeAnalyzer.runtimeScanner.eveConnector.image.pullPolicy | default .Values.global.image.pullPolicy }}
        ports:
          - name: api
            containerPort: 7000
            protocol: TCP
        resources:
{{ toYaml .Values.nodeAnalyzer.runtimeScanner.eveConnector.resources | indent 10 }}
        env:
          # authentication token for Snyk to EVE client communication taken from secret
          - name: CLIENT_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: sysdig-eve-secret
                key: token
          # DNS name used in self-signed certificate
          - name: CERT_DNS_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ template "nodeAnalyzer.fullname" . }}-eveconnector
                key: cert_dns_name
          # kubernetes cluster name where EVE Client and Snyk are installed
          - name: CLUSTER_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ template "nodeAnalyzer.fullname" . }}-eveconnector
                key: cluster_name
          # agent authentication token for EVE client to Sysdig BE comm.
          - name: SYSDIG_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                {{- if not ( include "nodeAnalyzer.accessKeySecret" . ) }}
                name: {{ template "nodeAnalyzer.fullname" . }}
                {{- else }}
                name: {{ ( include "nodeAnalyzer.accessKeySecret" . ) }}
                {{- end }}
                key: access-key
          # base URL for Sysdig Secure
          - name: SYSDIG_API_URL
            valueFrom:
              configMapKeyRef:
                name: {{ template "nodeAnalyzer.fullname" . }}-eveconnector
                key: api_endpoint
          # whether to check SSL certificate of Sysdig
          - name: SYSDIG_API_VERIFY_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: {{ template "nodeAnalyzer.fullname" . }}-eveconnector
                key: ssl_verify_certificate
                optional: true
          # proxy settings
          - name: HTTP_PROXY
            valueFrom:
              configMapKeyRef:
                name: {{ template "nodeAnalyzer.fullname" . }}-eveconnector
                key: http_proxy
                optional: true
          - name: HTTPS_PROXY
            valueFrom:
              configMapKeyRef:
                name: {{ template "nodeAnalyzer.fullname" . }}-eveconnector
                key: https_proxy
                optional: true
          - name: NO_PROXY
            valueFrom:
              configMapKeyRef:
                name: {{ template "nodeAnalyzer.fullname" . }}-eveconnector
                key: no_proxy
                optional: true
          {{- if eq (include "sysdig.custom_ca.enabled"  (dict "global" .Values.global.ssl "component" .Values.nodeAnalyzer.ssl)) "true" }}
          - name: SSL_CERT_FILE
            value: /ca-certs/{{- include "sysdig.custom_ca.keyName"  (dict "global" .Values.global.ssl "component" .Values.nodeAnalyzer.ssl) -}}
          {{- end }}
        volumeMounts:
          {{- if eq (include "sysdig.custom_ca.enabled"  (dict "global" .Values.global.ssl "component" .Values.nodeAnalyzer.ssl)) "true" }}
          - name: ca-cert
            mountPath: /ca-certs
            readOnly: true
          {{- end }}
{{- end }}
