{{- if and .Values.nodeAnalyzer.deploy (not (include "nodeAnalyzer.gke.autopilot" .)) (or .Values.nodeAnalyzer.runtimeScanner.deploy .Values.secure.vulnerabilityManagement.newEngineOnly) .Values.nodeAnalyzer.runtimeScanner.eveConnector.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "nodeAnalyzer.fullname" . }}-eveconnector
  namespace: {{ include "nodeAnalyzer.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "nodeAnalyzer.name" . }}-eveconnector
{{ include "nodeAnalyzer.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "nodeAnalyzer.name" . }}-eveconnector
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 443
    targetPort: 7000
{{- end }}
