{{- if and .Values.nodeAnalyzer.deploy (not (include "nodeAnalyzer.gke.autopilot" .)) (or .Values.nodeAnalyzer.runtimeScanner.deploy .Values.secure.vulnerabilityManagement.newEngineOnly) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-runtime-scanner
  namespace: {{ include "nodeAnalyzer.namespace" . }}
  labels:
{{ include "nodeAnalyzer.labels" . | indent 4 }}
data:
  api_endpoint: https://{{ include "nodeAnalyzer.apiEndpoint" . }}
  cluster_name: {{ required "A valid clusterName is required" (include "nodeAnalyzer.clusterName" . ) }}
  ssl_verify_certificate: {{ include "runtimeScanner.sslVerifyCertificate" . }}
  {{- if (.Values.nodeAnalyzer.runtimeScanner.debug | default .Values.nodeAnalyzer.debug) }}
  debug: "{{ .Values.nodeAnalyzer.runtimeScanner.debug | default .Values.nodeAnalyzer.debug }}"
  {{- end }}
  {{- if (.Values.nodeAnalyzer.runtimeScanner.httpProxy | default .Values.nodeAnalyzer.httpProxy | default .Values.global.proxy.httpProxy) }}
  http_proxy: {{ .Values.nodeAnalyzer.runtimeScanner.httpProxy | default .Values.nodeAnalyzer.httpProxy | default .Values.global.proxy.httpProxy }}
  {{- end -}}
  {{- if (.Values.nodeAnalyzer.runtimeScanner.httpsProxy | default .Values.nodeAnalyzer.httpsProxy | default .Values.global.proxy.httpsProxy) }}
  https_proxy: {{ .Values.nodeAnalyzer.runtimeScanner.httpsProxy | default .Values.nodeAnalyzer.httpsProxy | default .Values.global.proxy.httpsProxy }}
  {{- end -}}
  {{- if (.Values.nodeAnalyzer.runtimeScanner.noProxy | default .Values.nodeAnalyzer.noProxy | default .Values.global.proxy.noProxy) }}
  no_proxy: {{ .Values.nodeAnalyzer.runtimeScanner.noProxy | default .Values.nodeAnalyzer.noProxy | default .Values.global.proxy.noProxy }}
  {{- end -}}
  {{- if .Values.nodeAnalyzer.runtimeScanner.settings.eveEnabled }}
  eve_enabled: "true"
  {{- end -}}
  {{- if hasKey .Values.nodeAnalyzer.runtimeScanner "eveConnector" }}
  eve_integration_enabled: "true"
  {{- end -}}
  {{- if hasKey .Values.nodeAnalyzer.runtimeScanner "settings" }}
  prom_port: {{ .Values.nodeAnalyzer.runtimeScanner.settings.prometheusPort | default 25001 | quote }}
  {{- end -}}

  {{- if .Values.nodeAnalyzer.runtimeScanner.settings.maxImageSizeAllowed }}
  max_image_size_allowed: {{ .Values.nodeAnalyzer.runtimeScanner.settings.maxImageSizeAllowed | int64 | quote }}
  {{- end -}}
  {{- if .Values.nodeAnalyzer.runtimeScanner.settings.maxFileSizeAllowed }}
  analyzer.maxFileSizeAllowed: {{ .Values.nodeAnalyzer.runtimeScanner.settings.maxFileSizeAllowed | int64 | quote }}
  {{- end -}}
  {{- if .Values.nodeAnalyzer.runtimeScanner.settings.vulnerabilityDBVersion }}
  vuln_db_version: {{ .Values.nodeAnalyzer.runtimeScanner.settings.vulnerabilityDBVersion | quote }}
  {{- end -}}
{{- end }}
