{{- if or (and .Values.nodeAnalyzer.deploy (not .Values.gke.autopilot) .Values.nodeAnalyzer.runtimeScanner.deploy) .Values.secure.vulnerabilityManagement.newEngineOnly }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nodeAnalyzer.fullname" . }}-runtime-scanner
  labels:
{{ include "nodeAnalyzer.labels" . | indent 4 }}
data:
  api_endpoint: https://{{ required "A valid apiEndpoint is required" (include "nodeAnalyzer.apiEndpoint" .) }}
  cluster_name: {{ required "A valid .Values.clusterName is required" (include "nodeAnalyzer.clustername" . ) }}
  {{- if hasKey .Values.nodeAnalyzer "sslVerifyCertificate" }}
  ssl_verify_certificate: "{{ .Values.nodeAnalyzer.sslVerifyCertificate }}"
  {{- end }}
  debug: "{{ .Values.nodeAnalyzer.debug | default false }}"
  {{- if .Values.nodeAnalyzer.httpProxy }}
  http_proxy: {{ .Values.nodeAnalyzer.httpProxy }}
  {{- end -}}
  {{- if .Values.nodeAnalyzer.httpsProxy }}
  https_proxy: {{ .Values.nodeAnalyzer.httpsProxy }}
  {{- end -}}
  {{- if .Values.nodeAnalyzer.noProxy }}
  no_proxy: {{ .Values.nodeAnalyzer.noProxy }}
  {{- end -}}
  {{- if .Values.nodeAnalyzer.eveEnabled }}
  eve_enabled: "true"
  {{- end -}}
  {{- if hasKey .Values.nodeAnalyzer.runtimeScanner "eveConnector" }}
  eve_integration_enabled: "true"
  {{- end -}}
  {{- if hasKey .Values.nodeAnalyzer.runtimeScanner "settings" }}
  prom_port: {{ .Values.nodeAnalyzer.runtimeScanner.settings.prometheusPort | default 25001 | quote }}
  {{- end -}}
{{- end }}
