{{- if and .Values.nodeAnalyzer.deploy (not (include "nodeAnalyzer.gke.autopilot" .)) (or .Values.nodeAnalyzer.runtimeScanner.deploy .Values.secure.vulnerabilityManagement.newEngineOnly) .Values.nodeAnalyzer.runtimeScanner.eveConnector.deploy }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sysdig-eve-secret
  namespace: {{ include "nodeAnalyzer.namespace" . }}
  labels:
{{ include "nodeAnalyzer.labels" . | indent 4 }}
type: Opaque
data:
  endpoint: {{ include "eveconnector.host" . | printf "https://%s" | b64enc | quote }}
  token: {{ include "eveconnector.token" . }}
{{- end }}
{{- if eq (include "sysdig.custom_ca.useValues"  (dict "global" .Values.global.ssl "component" .Values.nodeAnalyzer.ssl)) "true" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nodeAnalyzer.fullname" . }}-eveconnector-ca
  namespace: {{ include "nodeAnalyzer.namespace" . }}
  labels:
{{ include "nodeAnalyzer.labels" . | indent 4 }}
data:
  {{ include "sysdig.custom_ca.keyName" (dict "global" .Values.global.ssl "component" .Values.nodeAnalyzer.ssl) }}: {{ include "sysdig.custom_ca.cert" (dict "global" .Values.global.ssl "component" .Values.nodeAnalyzer.ssl "Files" .Subcharts.common.Files) | b64enc | quote }}
{{- end }}
