apiVersion: v2
name: kspm-collector
description: Sysdig KSPM collector
version: 0.16.2
appVersion: 1.39.3
keywords:
  - monitoring
  - security
  - alerting
  - metric
  - troubleshooting
  - run-time
home: https://www.sysdig.com/
icon: https://avatars.githubusercontent.com/u/5068817?s=200&v=4
sources:
  - https://app.sysdigcloud.com/#/settings/user
  - https://github.com/draios/sysdig
maintainers:
  - name: chen-shmilovich-sysdig
    email: chen.shmilovich@sysdig.com
dependencies:
  - name: common
    # repository: https://charts.sysdig.com
    repository: file://../common
    version: ~1.3.1
