apiVersion: v2
name: cloud-scanning
description: Sysdig Cloud Scanning

type: application
version: 0.4.1
appVersion: 0.11.3
home: https://sysdiglabs.github.io/cloud-connector

maintainers:
  - name: airadier
    email: alvaro.iradier@sysdig.com
  - name: nestorsalceda
    email: nestor.salceda@sysdig.com
