{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "agent.fullname" .}}
  labels:
{{ include "agent.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "agent.serviceAccountName" .}}
    namespace: {{ include "agent.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ template "agent.fullname" .}}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
