apiVersion: v1
description: Sysdig IBM MCM Nav Menu integration
name: sysdig-mcm-navmenu
version: 1.2.0
appVersion: 1.0.0
home: https://www.sysdig.com/
icon: https://478h5m1yrfsa3bbe262u7muv-wpengine.netdna-ssl.com/wp-content/uploads/2019/02/Shovel_600px.png
maintainers:
    - name: airadier
      email: alvaro.iradier@sysdig.com
