apiVersion: v1
name: sysdig-stackdriver-bridge
version: 1.2.0
appVersion: 0.0.7
description: Sysdig Monitor and Secure agent
keywords:
  - monitoring
  - security
  - alerting
  - metric
  - troubleshooting
  - run-time
home: https://www.sysdig.com/
icon: https://avatars.githubusercontent.com/u/5068817?s=200&v=4
sources:
  - https://app.sysdigcloud.com/#/settings/user
  - https://github.com/draios/sysdig
maintainers:
  - name: bencer
    email: jorge.salamero@sysdig.com
  - name: nestorsalceda
    email: nestor.salceda@sysdig.com
  - name: echoboomer
    email: scott@echoboomer.net
