apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-monitor
  labels:
    app: {{ template "name" . }}-monitor
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    inmenu: "true"
  annotations:
    name: Sysdig Monitor # NavMenu: the display name that will show in the menu
    id: {{ .Values.service.monitorMenuId }} # NavMenu:  The id of the top-level menu item to attach to
    roles: ClusterAdministrator,Administrator,Operator,Viewer  # NavMenu: A list of roles you want to be able to view TA in the menu
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
