{{- if and (include "cluster.container_vulnerability_management_enabled" .) (not .Values.cluster.exclude_lease_creation) }}
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: {{ include "cluster.container_vulnerability_management_lease_name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
spec:
{{- $lease := lookup "coordination.k8s.io/v1" "Lease" .Release.Namespace (include "cluster.container_vulnerability_management_lease_name" .) -}}
{{- if $lease -}}
  {{- $lease.spec | toYaml | nindent 2 -}}
{{- end -}}
{{- end -}}
