{{- if (include "cluster.container_vulnerability_management_enabled" .) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cluster.container_vulnerability_management_service_name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
    {{- with .Values.cluster.service.labels }}
        {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.cluster.service.annotations }}
  annotations:
    {{- toYaml .Values.cluster.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.cluster.service.type }}
  ports:
    - port: 4222
      targetPort: cvm-nats
      protocol: TCP
      name: nats
    {{- if (include "cluster.admission_control_container_vulnerability_management_enabled" .) }}
    - port: 9999
      targetPort: cvm-grpc
      protocol: TCP
      name: grpc
    {{- end }}
# NOTE: selector is intentionally left empty. Cluster Shield will implement a controller to handle the Endpoints resource associated with this service
{{- end }}
