apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "host.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "host.workload_labels" . | nindent 4 }}
  annotations:
    {{- include "host.workload_annotations" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "host.selector_labels" . | nindent 6 }}
  updateStrategy:
    {{- toYaml .Values.host.update_strategy | nindent 4 }}
  template:
    metadata:
      name: {{ template "host.fullname" . }}
      labels:
        {{- include "host.pod_labels" . | nindent 8 }}
      annotations:
        {{- include "host.pod_annotations" . | nindent 8 }}
    spec:
      hostNetwork: true
      dnsPolicy: {{ default "ClusterFirstWithHostNet" .Values.host.dns_policy }}
      hostPID: true
      {{- if .Values.host.host_aliases }}
      hostAliases:
        {{ toYaml .Values.host.host_aliases | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "host.service_account_name" . }}
      {{- if (include "host.has_priority_class" .) }}
      priorityClassName: "{{ include "host.priority_class_name" . }}"
      {{- end }}
      tolerations:
        {{- include "host.tolerations" . | nindent 8 }}
      affinity:
        {{- include "host.affinity" . | nindent 8 }}
      nodeSelector:
        {{- include "host.node_selector" . | nindent 8 }}
      imagePullSecrets:
        {{- toYaml .Values.host.image.pull_secrets | nindent 8 }}
      {{- if not (include "host.driver.is_universal_ebpf" .) }}
      initContainers:
        - name: sysdig-host-shield-kmodule
          image: {{ include "host.kmodule_image" . }}
          imagePullPolicy: {{ .Values.host.image.pull_policy | default "IfNotPresent" }}
          securityContext:
            privileged: true
            runAsNonRoot: false
            runAsGroup: 0
            runAsUser: 0
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
            capabilities:
              drop:
                - ALL
          resources:
            {{- (include "host.kmodule_resources" .) | nindent 12 }}
          env:
            {{- if (include "host.driver.is_ebpf" .) }}
            - name: SYSDIG_BPF_PROBE
              value: ""
            - name: SYSDIG_AGENT_DRIVER
              value: "legacy_ebpf"
            {{- end }}
            {{- if (include "common.proxy.enabled" .) }}
            {{- include "common.proxy.envs" . | nindent 12 }}
            {{- end }}
            {{- include "common.custom_ca.envs" (merge (dict) . (dict "CACertsPath" "/opt/draios/certificates/")) | nindent 12 }}
          volumeMounts:
            {{- /* Autopilot = false */}}
            {{- if not (include "common.cluster_type.is_gke_autopilot" .) }}
            - mountPath: /etc/modprobe.d
              name: modprobe-d
              readOnly: true
            - mountPath: /host/boot
              name: boot-vol
              readOnly: true
            - mountPath: /host/etc
              name: etc-vol
              readOnly: true
            - mountPath: /host/lib/modules
              name: modules-vol
              readOnly: true
            - mountPath: /host/usr
              name: usr-vol
              readOnly: true
            {{- if (include "host.driver.is_ebpf" .) }}
            - mountPath: /root/.sysdig
              name: bpf-probes
            - mountPath: /sys/kernel/debug
              name: sys-tracing
              readOnly: true
            {{- end }}
            {{- end }}
          {{- /* Autopilot = true */}}
          {{- if (include "common.cluster_type.is_gke_autopilot" .) }}
            - mountPath: /host/boot
              name: boot-vol
              readOnly: true
            - mountPath: /host/etc/os-release
              name: osrel
              readOnly: true
          {{- end }}
      {{- end }}
      containers:
        - name: sysdig-host-shield
          image: {{ include "host.shield_image" . }}
          imagePullPolicy: {{ .Values.host.image.pull_policy }}
          resources:
            {{- (include "host.resources" .) | nindent 12 }}
          securityContext:
            {{- (include "host.security_context" .) | nindent 12 }}
          env:
            - name: K8S_NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- if and (include "host.driver.is_ebpf" .) (not (include "host.driver.is_universal_ebpf" .)) }}
            - name: SYSDIG_BPF_PROBE
              value:
            {{- end }}
            {{- if (include "host.driver.is_universal_ebpf" .) }}
            - name: SYSDIG_AGENT_DRIVER
              value: universal_ebpf
            {{- else if and (include "host.driver.is_legacy_ebpf" .) (not (include "common.cluster_type.is_gke_autopilot" .)) }}
            - name: SYSDIG_AGENT_DRIVER
              value: legacy_ebpf
            {{- end }}
            {{- if (include "common.proxy.enabled" .) }}
            {{- include "common.proxy.envs" . | nindent 12 }}
            {{- end }}
            {{- include "common.custom_ca.envs" (merge (dict) . (dict "CACertsPath" "/opt/draios/certificates/")) | nindent 12 }}
            {{- if (include "host.rapid_response_enabled" .) }}
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "host.rapid_response_password_secret" . }}
                  key: {{ include "host.rapid_response_password_secret_key" . }}
            {{- end }}
            {{- include "host.env" . | nindent 12 }}
            {{ if or .Values.features.posture.host_posture.enabled (dig "kspm_analyzer" "enabled" false .Values.host.additional_settings) }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- end }}
          ports:
            {{- if or .Values.features.posture.host_posture.enabled (dig "kspm_analyzer" "enabled" false .Values.host.additional_settings) }}
            - containerPort: {{ dig "kspm_analyzer" "port" 12000 .Values.host.additional_settings }}
              name: kspm-analyzer
            {{- end }}
            {{- if (dig "prometheus_exporter" "enabled" false .Values.host.additional_settings) }}
            - containerPort: {{ regexFind "[0-9]+$" (dig "prometheus_exporter" "listen_url" "0.0.0.0:9544" .Values.host.additional_settings) }}
              name: metrics
            {{- end }}
          readinessProbe:
            httpGet:
              host: 127.0.0.1
              path: /healthz
              port: 24483
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 9
          volumeMounts:
          {{- /* Custom CA */}}
          {{- include "common.custom_ca.volume_mount" (merge (dict) . (dict "CACertsPath" "/opt/draios/certificates/")) | nindent 12 }}
          {{- /* Always requested */}}
            - mountPath: /host/dev
              name: dev-vol
            - mountPath: /host/usr
              name: usr-vol
              readOnly: true
            - mountPath: /host/proc
              name: proc-vol
              readOnly: true
            - mountPath: /host/run
              name: run-vol
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /opt/draios/etc/kubernetes/config
              name: host-shield-config
            - mountPath: /opt/draios/etc/kubernetes/secrets
              name: host-shield-secrets
            - mountPath: /etc/podinfo
              name: podinfo
          {{- /* Autopilot = false */}}
          {{- if not (include "common.cluster_type.is_gke_autopilot" .) }}
            - mountPath: /host/etc
              name: etc-vol
              readOnly: true
            - mountPath: /host/var/lib
              name: varlib-vol
            - mountPath: /host/var/data
              name: vardata-vol
            - mountPath: /host/var/run
              name: varrun-vol
            {{- if (include "host.driver.is_ebpf" .) }}
            - mountPath: /root/.sysdig
              name: bpf-probes
            - mountPath: /sys/kernel/debug
              name: sys-tracing
              readOnly: true
            {{- end }}
          {{- end }}

          {{- /* Autopilot = true */}}
          {{- if (include "common.cluster_type.is_gke_autopilot" .) }}
            - mountPath: /host/etc/os-release
              name: osrel
              readOnly: true
            - mountPath: /host/var/run/containerd/containerd.sock
              name: containerdsock-vol
          {{- end }}

          {{- if (include "host.need_host_root" .) }}
            - mountPath: /host
              name: host-root
          {{- if not (eq (include "host.response_actions_enabled" .) "true") }}
              readOnly: true
          {{- end }}
          {{- if .Values.features.posture.host_posture.enabled }}
            - mountPath: /host/tmp
              name: host-tmp
          {{- end }}
          {{- end }}
          {{- if .Values.features.investigations.event_forwarder.enabled }}
            - mountPath: /opt/draios/etc/local_forwarder_config.yaml
              name: local-forwarder-config
              subPath: local_forwarder_config.yaml
          {{- end }}
          {{- include "host.volume_mounts" . | nindent 12 }}
      volumes:
      {{- /* Always requested */}}
        - name: dev-vol
          hostPath:
            path: /dev
        - name: usr-vol
          hostPath:
            path: /usr
        - name: proc-vol
          hostPath:
            path: /proc
        - name: run-vol
          hostPath:
            path: /run
        - name: dshm
          emptyDir:
            medium: Memory
        - name: host-shield-config
          configMap:
            name: {{ include "host.fullname" . }}
        - name: host-shield-secrets
          secret:
            secretName: {{ include "common.credentials.access_key_secret_name" . }}
        - name: podinfo
          downwardAPI:
            defaultMode: 420
            items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
                path: namespace
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
                path: name

      {{- /* Custom CA */}}
      {{- include "common.custom_ca.volume" . | nindent 8 }}

      {{- /* Autopilot = false */}}
      {{- if not  (include "common.cluster_type.is_gke_autopilot" .) }}
        - name: modprobe-d
          hostPath:
            path: /etc/modprobe.d
        - name: boot-vol
          hostPath:
            path: /boot
        - name: modules-vol
          hostPath:
            path: /lib/modules
        - name: varrun-vol
          hostPath:
            path: /var/run
        - name: etc-vol
          hostPath:
            path: /etc
        - name: varlib-vol
          hostPath:
            path: /var/lib
        - name: vardata-vol
          hostPath:
            path: /var/data
            type: DirectoryOrCreate
        {{- if (include "host.driver.is_ebpf" .) }}
        - name: bpf-probes
          emptyDir: {}
        - name: sys-tracing
          hostPath:
            path: /sys/kernel/debug
        {{- end }}
      {{- end }}

      {{- /* Autopilot = true */}}
      {{- if (include "common.cluster_type.is_gke_autopilot" .) }}
        - name: boot-vol
          hostPath:
            path: /boot
        - name: osrel
          hostPath:
            path: /etc/os-release
        - name: containerdsock-vol
          hostPath:
            path: /var/run/containerd/containerd.sock
      {{- end }}

      {{- if (include "host.need_host_root" .) }}
        - name: host-root
          hostPath:
            path: /
      {{- if .Values.features.posture.host_posture.enabled }}
        - name: host-tmp
          hostPath:
            path: /tmp
      {{- end }}
      {{- end }}
      {{- if .Values.features.investigations.event_forwarder.enabled }}
        - name: local-forwarder-config
          secret:
            {{- if eq .Values.features.investigations.event_forwarder.existing_secret "" }}
            secretName: {{ include "host.local_forwarder_secret_name" . }}
            {{- else }}
            secretName: {{ .Values.features.investigations.event_forwarder.existing_secret }}
            {{- end }}
      {{- end }}
      {{- include "host.volumes" . | nindent 8 }}
