{{- if (include "common.cluster_type.is_gke_autopilot" .) -}}
{{- if .Values.host.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "host.allowlist_waiter.fullname" . }}
  labels:
    {{- include "host.rbac_labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "-5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "host.allowlist_waiter.fullname" . }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "host.allowlist_waiter.service_account_name" . }}
{{- end }}
{{- end -}}
