apiVersion: v2
name: admission-controller
description: Sysdig Admission Controller using Sysdig Secure inline image scanner
type: application
version: 0.16.6
appVersion: 3.9.47
home: https://sysdiglabs.github.io/admission-controller/
icon: https://avatars.githubusercontent.com/u/5068817?s=200&v=4
maintainers:
  - name: sysdiglabs
dependencies:
  - name: common
    repository: file://../common
    version: ~1.3.1
