apiVersion: v2
name: registry-scanner
description: Sysdig Registry Scanner
type: application
home: https://www.sysdig.com/
icon: https://avatars.githubusercontent.com/u/5068817?s=200&v=4
version: 1.3.1
appVersion: 0.2.70
maintainers:
  - name: sysdiglabs
