apiVersion: v2
name: registry-scanner
description: Sysdig Registry Scanner
type: application
home: https://sysdiglabs.github.io/registry-scanner/
icon: https://478h5m1yrfsa3bbe262u7muv-wpengine.netdna-ssl.com/wp-content/uploads/2019/02/Shovel_600px.png
version: 0.0.28
appVersion: 0.1.5
maintainers:
  - name: airadier
    email: alvaro.iradier@sysdig.com
  - name: guipal
    email: guillermo@sysdig.com
