apiVersion: v2
name: registry-scanner
description: Sysdig Registry Scanner
type: application
home: https://sysdiglabs.github.io/registry-scanner/
icon: https://478h5m1yrfsa3bbe262u7muv-wpengine.netdna-ssl.com/wp-content/uploads/2019/02/Shovel_600px.png
version: 1.0.0
appVersion: 0.2.28
maintainers:
  - name: airadier
    email: alvaro.iradier@sysdig.com
  - name: hayk99
    email: hayk.kocharyan@sysdig.com
  - name: wideawakening
    email: irune.prado@sysdig.com
  - name: tembleking
    email: fede.barcelona@sysdig.com
  - name: miketnt
    email: miguel.baztan@sysdig.com
  - name: jprieto92
    email: javier.prieto@sysdig.com
