apiVersion: v2
name: registry-scanner
description: Sysdig Registry Scanner
type: application
home: https://www.sysdig.com/
icon: https://avatars.githubusercontent.com/u/5068817?s=200&v=4
version: 1.10.3
appVersion: 0.11.2
maintainers:
  - name: sysdiglabs
