apiVersion: v2
name: cluster-scanner
description: Sysdig Cluster Scanner

type: application
version: 0.14.2
appVersion: "0.1.0"
home: https://www.sysdig.com/

maintainers:
  - name: sysdiglabs
dependencies:
  - name: common
    # repository: https://charts.sysdig.com
    repository: file://../common
    version: ~1.3.1
