apiVersion: v2
name: cloud-connector
description: Sysdig Cloud Connector

type: application
version: 0.7.25
appVersion: 0.16.41
home: https://sysdiglabs.github.io/cloud-connector

maintainers:
  - name: hayk99
    email: hayk.kocharyan@sysdig.com
  - name: tembleking
    email: fede.barcelona@sysdig.com
  - name: wideawakening
    email: irune.prado@sysdig.com
  - name: regiluze
    email: ruben.eguiluz@sysdig.com
  - name: penguinjournals
    email: david.gonzalez@sysdig.com
  - name: miketnt
    email: miguel.baztan@sysdig.com
  - name: jprieto92
    email: javier.prieto@sysdig.com
