apiVersion: v2
name: cloud-connector
description: Sysdig Cloud Connector

type: application
version: 0.8.8
appVersion: 0.16.48
home: https://sysdiglabs.github.io/cloud-connector

maintainers:
  - name: sysdiglabs
