apiVersion: v2
name: cloud-connector
description: Sysdig Cloud Connector

type: application
version: 0.7.3
appVersion: 0.14.1
home: https://sysdiglabs.github.io/cloud-connector

maintainers:
  - name: nestorsalceda
    email: nestor.salceda@sysdig.com
