project:
  name: Cloud Connector
  shortName: Cloud Connector
  url: https://docs.sysdig.com/en/docs/installation/sysdig-secure-for-cloud/
  description: |
    This chart deploys Sysdig Cloud Connector on your Kubernetes cluster, enabling Threat Detection and Image Scanning for the  AWS, GCP, and Azure Cloud providers. Use this method only if your Sysdig representative recommends it to you. For the official installation instruction, see [Install Sysdig Secure for Cloud ](https://docs.sysdig.com/en/docs/installation/sysdig-secure-for-cloud/). 
  app: the Sysdig Cloud Connector
repository:
  url: https://charts.sysdig.com
  name: sysdig
chart:
  name: cloud-connector
#  version: v0.9.0-rc.0
#  values: "-- generate from values file --"
  valuesExample: "sysdig.secureAPIToken=<YOUR-SECURE-KEY>"
prerequisites:
- "Helm 3"
- "Sysdig Secure API Token"

release:
  name: cloud-connector
  namespace: cloud-connector
