# If someone with write access comments "/approve-test-run" on a pull request, emit a repository_dispatch event
name: Approve Test Run

on:
  issue_comment:
    types: [created]

jobs:
  approve-test-run:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.TOOLS_JENKINS_ADMIN_ACCESS_GITHUB_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          issue-type: pull-request
          commands: approve-test-run
          permission: write
