name: PR Labeler

on:
  - pull_request_target

jobs:
  pr-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4.0.3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
