name: Update the sysdig-deploy chart versions
run-name: github actions is updating sysdig-deploy versions based on dependencies
on:
  push:
    branches:
      - master
jobs:
  update-sysdig-deploy-version:
    runs-on: tools-runner-small
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if dependent charts were modified or not
        uses: tj-actions/changed-files@v35
        id: dependent_files
        with:
          files: |
            charts/node-analyzer/*
            charts/agent/*
            charts/kspm-collector/*
            charts/rapid-response/*
            charts/admission-controller/*

      - name: Install YQ
        if: steps.dependent_files.outputs.any_changed == 'true'
        uses: dcarbone/install-yq-action@v1.1.0

      - name: run the script
        if: steps.dependent_files.outputs.any_changed == 'true'
        run: scripts/sysdig-deploy/update-sysdig-deploy.sh

      - name: Configure Git
        if: steps.dependent_files.outputs.any_changed == 'true'
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Create Pull Request
        if: steps.dependent_files.outputs.any_changed == 'true'
        uses: peter-evans/create-pull-request@v5.0.1
        with:
          title: "chore(sysdig-deploy): Automatic version bump due to updated dependencies"
          base: master
          delete-branch: true
          labels: automated PR
          token: ${{ secrets.TOOLS_JENKINS_ADMIN_ACCESS_GITHUB_TOKEN }}
          add-paths: charts/sysdig-deploy/Chart.yaml
          commit-message: "chore: Updating sysdig-deploy version"
