name: Update the Sysdig Operator Repo

on:
  release:
    types: [published]

jobs:
  dispatch:
    runs-on: tools-runner-small
    steps:
      - name: filter release tag
        id: filter_tag
        run: |
            if [[ "${{ github.event.release.tag_name }}" =~ ^sysdig-[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=tag_match::true
            fi

      - name: update sysdig-operator
        if: steps.filter_tag.outputs.tag_match == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TOOLS_JENKINS_ADMIN_ACCESS_GITHUB_TOKEN }}
          repository: sysdiglabs/sysdig-operator
          event-type: sysdig-release
          client-payload: '{"tag": "${{ github.event.release.tag_name }}" }'
