{{- if and (not (include "deploy-nia" .)) .Values.nodeAnalyzer.deploy .Values.nodeAnalyzer.runtimeScanner.deploy .Values.nodeAnalyzer.runtimeScanner.eveConnector.deploy }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sysdig-eve-secret
  labels:
{{ include "sysdig.labels" . | indent 4 }}
type: Opaque
data:
  endpoint: {{ include "eveconnector.host" . | printf "https://%s" | b64enc | quote }}
  token: {{ include "eveconnector.token" . }}
{{- end }}
