apiVersion: v2
appVersion: 13.4.0
dependencies:
- name: common
  repository: file://../common
  version: ~1.3.1
description: Sysdig Monitor and Secure agent
home: https://www.sysdig.com/
icon: https://avatars.githubusercontent.com/u/5068817?s=200&v=4
keywords:
- monitoring
- security
- alerting
- metric
- troubleshooting
- run-time
maintainers:
- email: alberto.barba@sysdig.com
  name: AlbertoBarba
- email: adam.roberts@sysdig.com
  name: aroberts87
- email: francesco.furlan@sysdig.com
  name: francesco-furlan
- email: gerlando.falauto@sysdig.com
  name: iurly
- email: marcovito.moscaritolo@sysdig.com
  name: mavimo
name: agent
sources:
- https://app.sysdigcloud.com/#/settings/user
- https://github.com/draios/sysdig
type: application
version: 1.29.4
