apiVersion: v2
name: agent
description: Sysdig Monitor and Secure agent
type: application
# currently matching sysdig 1.14.32
version: 1.13.10
appVersion: 12.16.1
keywords:
  - monitoring
  - security
  - alerting
  - metric
  - troubleshooting
  - run-time
home: https://www.sysdig.com/
icon: https://avatars.githubusercontent.com/u/5068817?s=200&v=4
sources:
  - https://app.sysdigcloud.com/#/settings/user
  - https://github.com/draios/sysdig
maintainers:
  - name: AlbertoBarba
    email: alberto.barba@sysdig.com
  - name: aroberts87
    email: adam.roberts@sysdig.com
  - name: francesco-furlan
    email: francesco.furlan@sysdig.com
  - name: iurly
    email: gerlando.falauto@sysdig.com
  - name: mavimo
    email: marcovito.moscaritolo@sysdig.com
dependencies:
  - name: common
    # repository: https://charts.sysdig.com
    repository: file://../common
    version: ~1.2.1
